// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gfrddfryaryshgerwjij.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdmcmRkZnJ5YXJ5c2hnZXJ3amlqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0MTA0MDQsImV4cCI6MjA2Njk4NjQwNH0._wb-9dxFbQMN0wes1CB_G-sHuldo5WE0YjiGjGyufHI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});